name: news_paper_pdf
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  permission_handler:
  dio: ^5.4.0
  get_storage: ^2.1.1
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.2
  flutter_downloader: ^1.11.6
  path_provider: ^2.1.1
  upgrader: ^9.0.0
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.jpg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
